require_relative "board.rb"
require_relative "constants.rb"
require_relative "game.rb"
require_relative "move.rb"
require_relative "bitboard.rb"
require_relative "move_applier.rb"
require_relative "square.rb"

require_relative "move-generation/attacking"
require_relative "move-generation/base"
require_relative "move-generation/leaping"
require_relative "move-generation/pawns"
require_relative "move-generation/sliding"
require_relative "move-generation/legal"